# Generated by Django 2.0.2 on 2018-02-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Proje Adı')),
                ('members', models.TextField(blank=True, verbose_name='Üyeler')),
            ],
        ),
    ]
