# Generated by Django 2.0.2 on 2018-02-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20180208_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='follow.Project'),
        ),
    ]
