# Generated by Django 2.0.2 on 2018-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0006_auto_20180208_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Dosya Ekle'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='Yorum'),
        ),
    ]
