# Generated by Django 2.0.2 on 2018-02-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0007_auto_20180208_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_date', 'id']},
        ),
    ]
